/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'amatheny' at '6/25/15 1:59 PM' with Gradle 2.4
 *
 * @author amatheny, @date 6/25/15 1:59 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
