/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'amatheny' at '6/25/15 1:59 PM' with Gradle 2.4
 *
 * @author amatheny, @date 6/25/15 1:59 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
